/*
 * This source file was generated by the Gradle 'init' task
 */
package org.masumera;

import java.io.IOException;


import org.masumera.body.Album;
import org.masumera.body.Song;
import org.masumera.service.CallRequest;
import org.masumera.service.SaveFile;

public class App {
    public static void main(String[] args) {
    //
    // Song song = new Song("fireworks", 2, 5);
    // // song.setName("fire");
    // Song hero = new Song("mirai", 3, 8);
    //
    // System.out.println(song.getName());
    // System.out.println(song.getDuration());
    //
    // Album album = new Album(hero, "ella");
    //
    // System.out.println(album.getSong().getName());
    // System.out.println(album.getName());
    // 
    
    CallRequest query = new CallRequest();

    try {
    
    String result = query.queryApi("Viva la vida", "coldplay");
    System.out.println(result);

    SaveFile saveFile = new SaveFile();
    saveFile.sampleFile(result);
    
    } catch (InterruptedException | IOException e){
      System.out.println("error");
    }
    

    


    

    
    }
}
