/*
 * This source file was generated by the Gradle 'init' task
 */
package org.masumera;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestReporter;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
     @Test 
     void appHasAGreeting() {
         App classUnderTest = new App();
         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
         assertEquals("Hello", classUnderTest.getGreeting());
         
     }

}
